<a href="https://colab.research.google.com/github/NOdubT/Python/blob/main/Working_with_NumPy_and_Pandas_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount("/content/drive")
%cd /content/drive/MyDrive/MA/data

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/MA/data

In [ ]:
adult_data = pd.read_csv("adult.csv")
adult_data.head()

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25

# Прочитай набір даних із CSV-файлу та виконай очищення даних — видали усі рядки, які містять символ "?" у будь-яких стовпцях. Також перевір коректність даних (зарплата та зарплата у $K).

In [ ]:
adult_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      32561 non-null  int64
 1   age             32561 non-null  int64
 2   workclass       32561 non-null  object
 3   education       32561 non-null  object
 4   marital-status  32561 non-null  object
 5   occupation      32561 non-null  object
 6   relationship    32561 non-null  object
 7   race            32561 non-null  object
 8   sex             32561 non-null  object
 9   hours-per-week  32561 non-null  int64
 10  native-country  32561 non-null  object
 11  salary          32561 non-null  object
 12  salary K$       32561 non-null  int64
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

In [ ]:
(adult_data == "?").sum()

Unnamed: 0           0
age                  0
workclass         1836
education            0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
hours-per-week       0
native-country     583
salary               0
salary K$            0
dtype: int64

In [ ]:
adult_data = adult_data.replace("?", np.nan)
adult_data = adult_data.dropna()
(adult_data == "?").sum()

Unnamed: 0        0
age               0
workclass         0
education         0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
hours-per-week    0
native-country    0
salary            0
salary K$         0
dtype: int64

In [ ]:
adult_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      30162 non-null  int64
 1   age             30162 non-null  int64
 2   workclass       30162 non-null  object
 3   education       30162 non-null  object
 4   marital-status  30162 non-null  object
 5   occupation      30162 non-null  object
 6   relationship    30162 non-null  object
 7   race            30162 non-null  object
 8   sex             30162 non-null  object
 9   hours-per-week  30162 non-null  int64
 10  native-country  30162 non-null  object
 11  salary          30162 non-null  object
 12  salary K$       30162 non-null  int64
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

In [ ]:
adult_data.describe()

         Unnamed: 0           age  hours-per-week     salary K$
count  30162.000000  30162.000000    30162.000000  30162.000000
mean   16287.103242     38.437902       40.931238     73.968570
std     9383.401676     13.134665       11.979984     85.365144
min        0.000000     17.000000        1.000000     15.000000
25%     8178.250000     28.000000       40.000000     26.000000
50%    16285.500000     37.000000       40.000000     38.000000
75%    24401.750000     47.000000       45.000000     49.000000
max    32560.000000     90.000000       99.000000    349.000000

In [ ]:
adult_data["salary"].nunique()

2

In [ ]:
adult_data["salary"].value_counts()

salary
<=50K    22654
>50K      7508
Name: count, dtype: int64

In [ ]:
adult_data["check_salary"] = (
    ((adult_data["salary"] == "<=50K") & (adult_data["salary K$"] <= 50)) |
    ((adult_data["salary"] == ">50K") & (adult_data["salary K$"] > 50))
)

print(adult_data["check_salary"].value_counts())

check_salary
True    30162
Name: count, dtype: int64

In [ ]:
adult_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      30162 non-null  int64
 1   age             30162 non-null  int64
 2   workclass       30162 non-null  object
 3   education       30162 non-null  object
 4   marital-status  30162 non-null  object
 5   occupation      30162 non-null  object
 6   relationship    30162 non-null  object
 7   race            30162 non-null  object
 8   sex             30162 non-null  object
 9   hours-per-week  30162 non-null  int64
 10  native-country  30162 non-null  object
 11  salary          30162 non-null  object
 12  salary K$       30162 non-null  int64
 13  check_salary    30162 non-null  bool
dtypes: bool(1), int64(4), object(9)
memory usage: 3.3+ MB

In [ ]:
adult_data = adult_data.rename(columns={"Unnamed: 0": "id"})

In [ ]:
adult_data.head()

,id,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$,check_salary
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39,True
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35,True
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27,True
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43,True
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25,True

# Виведи на екран кількість чоловіків і жінок у наборі даних.

In [ ]:
print(adult_data["sex"].value_counts())

sex
Male      20380
Female     9782
Name: count, dtype: int64

# Знайди середній вік чоловіків у наборі даних.

In [ ]:
print(adult_data[adult_data["sex"] == "Male"]["age"].mean())

39.18400392541707

# Отримай відсоток людей з Польщі (native-country).

In [ ]:
print(adult_data["native-country"].unique())

['United-States' 'Cuba' 'Jamaica' 'India' 'Mexico' 'Puerto-Rico'
 'Honduras' 'England' 'Canada' 'Germany' 'Iran' 'Philippines' 'Poland'
 'Columbia' 'Cambodia' 'Thailand' 'Ecuador' 'Laos' 'Taiwan' 'Haiti'
 'Portugal' 'Dominican-Republic' 'El-Salvador' 'France' 'Guatemala'
 'Italy' 'China' 'South' 'Japan' 'Yugoslavia' 'Peru'
 'Outlying-US(Guam-USVI-etc)' 'Scotland' 'Trinadad&Tobago' 'Greece'
 'Nicaragua' 'Vietnam' 'Hong' 'Ireland' 'Hungary' 'Holand-Netherlands']

In [ ]:
print(adult_data[adult_data["native-country"] == "Poland"].shape[0] / adult_data.shape[0] * 100)

0.18566408063125786

# Перевір, чи є люди без вищої освіти (освіта: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), але із зарплатою > 50K.

In [ ]:
print(adult_data["education"].unique())

['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 '7th-8th' 'Doctorate' 'Assoc-voc' 'Prof-school' '5th-6th' '10th'
 'Preschool' '12th' '1st-4th']

In [ ]:
adult_data_filtered = adult_data[
    ~adult_data["education"].isin([
        "Bachelors", "Prof-school", "Assoc-acdm",
        "Assoc-voc", "Masters", "Doctorate"
    ])
    & adult_data["salary K$"] > 50
]

print(adult_data_filtered.head())

Empty DataFrame
Columns: [id, age, workclass, education, marital-status, occupation, relationship, race, sex, hours-per-week, native-country, salary, salary K$, check_salary]
Index: []

# Отримай статистику віку для кожного виду освіти. Використовуй groupby і describe для цього.

In [ ]:
print(adult_data.groupby(by="education")["age"].describe())

               count       mean        std   min   25%   50%   75%   max
education
10th           820.0  37.897561  16.225795  17.0  23.0  36.0  52.0  90.0
11th          1048.0  32.363550  15.089307  17.0  18.0  28.5  43.0  90.0
12th           377.0  32.013263  14.373710  17.0  19.0  28.0  41.0  79.0
1st-4th        151.0  44.622517  14.929051  19.0  33.0  44.0  56.0  81.0
5th-6th        288.0  41.649306  14.754622  17.0  28.0  41.0  53.0  82.0
7th-8th        557.0  47.631957  15.737479  17.0  34.0  49.0  60.0  90.0
9th            455.0  40.303297  15.335754  17.0  28.0  38.0  53.0  90.0
Assoc-acdm    1008.0  37.286706  10.509755  19.0  29.0  36.0  44.0  90.0
Assoc-voc     1307.0  38.246366  11.181253  19.0  30.0  37.0  45.0  84.0
Bachelors     5044.0  38.641554  11.577566  19.0  29.0  37.0  46.0  90.0
Doctorate      375.0  47.130667  11.471727  24.0  39.0  47.0  54.0  80.0
HS-grad       9840.0  38.640955  13.067730  17.0  28.0  37.0  48.0  90.0
Masters       1627.0  43.740012  10.735356  18.0  36.0  43.0  50.0  90.0
Preschool       45.0  41.288889  15.175672  19.0  30.0  40.0  53.0  75.0
Prof-school    542.0  44.249077  11.428098  25.0  36.0  43.0  50.0  90.0
Some-college  6678.0  36.135370  13.073528  17.0  25.0  35.0  45.0  90.0

# Порівняй зарплати одружених і неодружених чоловіків. Хто заробляє більше? (> 50K або < = 50K) Одружені чоловіки — це ті, у кого marital-status починається з Married. Інші — не одружені.

In [ ]:
pivot = pd.pivot_table(
    adult_data[adult_data["sex"] == "Male"],
    index=adult_data["marital-status"].str.startswith("Married"),
    columns="salary",
    values="age",
    aggfunc="count"
)

print(pivot)

salary          <=50K  >50K
marital-status
False            6932   673
True             7052  5723

# Отримай максимальну кількість годин на тиждень, яку працює людина. Скільки людей працює стільки ж годин на тиждень?

In [ ]:
print(np.max(adult_data["hours-per-week"]))

99

In [ ]:
print(adult_data[adult_data["hours-per-week"] == np.max(adult_data["hours-per-week"])].shape[0])

78